import Head from 'next/head';
import Image from 'next/image'
import img1 from '../public/muscular-fighter-practicing-some-kicks-260nw-552300403_1_800x600.jpg'
import img2 from '../public/modern-running-background_1017-7491_2_800x600.jpg'
import img3 from '../public/lunge_800x600.jpg'
import Slider from "react-slick";
import DummyJson from './api/DummyJson.json'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const settings = {
    dots: true,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    speed: 2000,
    // autoplaySpeed: 2000,
    cssEase: "linear",
  };
console.log(DummyJson.length);
  return (
    <>
      <Head>
        <title>Next js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </Head>
      <main>
{/* <h1>Hello World!!</h1> */}
<div className="hero bg-base-200 p-0">
<div className="hero min-h-screen bg-opacity-50" style={{ backgroundImage: `url(https://i.ibb.co/VwrbGyr/image.jpg)`}}>
  <div className="hero-overlay bg-opacity-20"></div>
  <div className="hero-content text-center text-neutral-content">
    <div className="max-w-md">
      <h1 className="mb-5 text-5xl font-bold">Hello there</h1>
      <p className="mb-5">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
      <button className="btn btn-primary">Get Started</button>
    </div>
  </div>
</div>
</div>

{/* slider section start from here */}
<div className='m-4'>
  <Slider {...settings}>
       {
        DummyJson.map((data)=>{
          return(
<div className="card w-84 bg-base-100 shadow-xl m-4 p-2 gap-3" key={data.id} >
<figure><img className='h-40 w-72 transition-all duration-1000 rounded-lg cursor-pointer filter grayscale hover:grayscale-0' src={data.image} alt="Shoes" /></figure>
<div className="">
  <h2 className="card-title">
    {data.name}
  </h2>
  <h1>{data.cost}</h1>
  {/* <div className="card-actions justify-end"> */}
    {/* <div className="badge badge-outline">Read More</div> */}
    {/* <div className="badge badge-outline">Products</div> */}
  {/* </div> */}
</div>
</div>
          )
        })
       }
  </Slider>
</div>

<div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2  bg-base-200 p-2'>
<div className="card w-full bg-base-100 shadow-xl">
  <div className="card-body">
    <h2 className="card-title">BEGINNER</h2>
    <Image className='rounded-lg' src={img2} alt='image' width={500}
  height={300}></Image>
    <p className='text-justify'>Everyone has different reasons for joining a gym but for anyone just starting out on their journey, understanding how to use equipment effectively can be confusing. These beginner gym workouts are ideal for various goals, whether you want to lose weight or burn fat, build muscle and strength, or improve your fitness.</p>
    <div className="card-actions justify-end">
      {/* <button className="btn btn-primary">See More</button> */}
    </div>
  </div>
</div>
<div className="card w-full bg-base-100 shadow-xl">
  <div className="card-body">
    <h2 className="card-title">ADVENCE</h2>
    <Image className='rounded-lg' src={img3} alt='image' width={500}
  height={300}></Image>
    <p className='text-justify'>Advanced bodybuilder workout suited to advanced lifters with at least 1 years lifting experience.
This advanced bodybuilder workout is designed to destroy each muscle group once a week over 5 days! Monday you will hit shoulders, Tuesday for arms, Wednesday for legs, Thursday for back and Friday for Chest. To look after the mid-section you will be doing 1 abdominal exercise at the end of each daily workout.</p>
    <div className="card-actions justify-end">
      {/* <button className="btn btn-primary">See More</button> */}
    </div>
  </div>
</div>
<div className="card w-full bg-base-100 shadow-xl">
  <div className="card-body">
    <h2 className="card-title">BOXING</h2>
    <Image className='rounded-lg' src={img1} alt='image' width={500}
  height={100}></Image>
    <p className='text-justify'>boxing punching is the proper technique used to execute each punch. Each type of punch has a specific technique that requires proper body mechanics, footwork, and hand positioning. For example, a jab involves a quick and straight punch with the lead hand, while a hook requires a circular motion of the arm and body to generate power</p>
    <div className="card-actions justify-end">
      {/* <button className="btn btn-primary">See More</button> */}
    </div>
  </div>
</div>
</div>
      </main>
    </>
  )
}
